services:
  api:
    build:
      context: ./api/
    image: nigeleke/lettersandnumbers-api
    restart: unless-stopped
    hostname: lettersandnumbersapi
    ports:
      - "8088:80"

  ui:
    build:
      context: ui-rust/
    image: nigeleke/lettersandnumbers-ui
    restart: unless-stopped
    hostname: lettersandnumbers
    ports:
      - "8080:80"
    depends_on:
      - api
