[package]
name = "letters-and-numbers-rust"
version = "0.1.0"
edition = "2018"

[dependencies]
comp = "0.2.1"
itertools = "0.10.1"
yew = "0.18"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
